### PR TITLE
enable flake8-commas and -quotes

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by danpalmer** [comment]
I'd suggest an alternative style for quotes (that can't be enforced by flake8-quotes).
- Strings that get output to a user should be in double quotes.
- All other strings in single quotes.

This makes it:
- Really obvious when something is "machine readable"
- Easier to grep for errors.
- Easier to add, for example, translations in the future (unlikely, but you never know).

**Comment by graingert** [comment]
@danpalmer that's going to be impossible to enforce here in an open source repo

**Comment by danpalmer** [comment]
It can be enforced manually quite easily.

**Comment by graingert** [comment]
@danpalmer I'm setting this so it's consistent, once someone goes around complying with the user-facing/vs token I'll remove flake8-quotes

**Comment by danpalmer** [comment]
...you mean flake8-quotes? (just checking for clarity in the future)

**Comment by graingert** [comment]
@danpalmer updated

**Pull request merged**
